import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Story Behind the Mission", description: "Meet the Singh Sisters and discover the mission behind their global education guidance." };

const sisters = [
  { name: "Anamika Singh, PhD", role: "Founder (France)", image: "/images/sister-anamika.png?v=20260821", position: "50% 16%", size: "cover" },
  { name: "Aparajita Singh, PhD", role: "Co-founder (Germany)", image: "/images/sister-aparajita.jpg?v=20260819", position: "50% 12%", size: "cover" },
  { name: "Ankita Singh, PhD", role: "Co-founder (United States)", image: "/images/sister-ankita.png?v=20260821", position: "50% 18%", size: "cover" },
 
];

export default function About() { return <>
  <section className="story-mission-hero"><div className="story-container story-mission-inner"><span className="section-kicker">Story Behind the Mission</span><h1>Three sisters. Three countries. One mission.</h1><p>To create a future in which every talented student, regardless of gender, geography, or socioeconomic background, has access to global educational and research opportunities.</p></div></section>
  <section className="sisters-section"><span className="section-kicker">The people behind the mission</span><h2>Meet the three sisters</h2><div className="story-container sister-grid">{sisters.map((sister) => <article className="sister-card" key={sister.name}><div className="sister-photo" style={{ backgroundImage: `url(${sister.image})`, backgroundPosition: sister.position, backgroundSize: sister.size }} role="img" aria-label={`Portrait of ${sister.name}`} /><h3>{sister.name}</h3><p>{sister.role}</p></article>)}</div></section>
  <section className="story-intro"><div className="story-container story-top-grid"><div className="story-photo story-founders-photo" /><div className="story-copy"><h2 className="story-primary-heading">Who We Are</h2><p>We are three sisters from Varanasi who refused to let geography, gender stereotypes, or limited access to opportunities define our futures. Education became our pathway to independence, resilience, and global careers across France, Germany, and the United States.</p><p>Having navigated international education ourselves, we understand how overwhelming the journey can feel. Singh Sisters exists to offer honest, personalised guidance so students can pursue opportunities with clarity and confidence.</p></div></div></section>
  <section className="why-exist-professional"><div className="story-container detail-grid"><div className="story-copy why-copy"><h2 className="story-primary-heading">Why We Exist</h2><p>Many capable students never pursue international education because they face limited guidance, financial uncertainty, lack of awareness, fear of rejection, or no access to experienced mentors.</p><ul><li>Clear, independent guidance</li><li>Realistic budget and program planning</li><li>Research and application mentorship</li><li>Support from people who understand the journey</li></ul><p><strong>We help bridge that gap — one student, one conversation, and one informed decision at a time.</strong></p></div><div className="story-photo story-indian-students-photo" /></div></section>
  <section className="founder-note"><div className="story-container founder-grid"><div className="story-copy"><span className="section-kicker">A personal message</span><h2>Note from the Founder</h2><p>I understand the pressure society puts on students — expectations from family, comparisons with relatives, and the silent weight that can affect well-being. I believe no dream is worth sacrificing your mental health.</p><p>As a woman in STEM, I deeply support women who dare to step into science and global careers. Singh Sisters is my way of offering honest guidance, encouragement, and understanding through this journey.</p><Link className="education-button" href="/book-consultation">Book your free consultation</Link></div><div className="story-photo story-founder-photo" role="img" aria-label={"Founder portrait at the Eiffel Tower"} /></div></section>
</>; }
